export const UI_CONFIG = {
  placeholders: {
    search: 'ค้นหาคำตอบ เช่น อิสลามกับความรุนแรง...',
    advancedSearch: 'เช่น อิสลามกับความรุนแรง, สตรีในอิสลาม...',
    aboutMe: 'บอกเล่าเกี่ยวกับตัวคุณ...',
    currentPassword: 'รหัสผ่านปัจจุบัน',
    newPassword: 'อย่างน้อย 6 ตัวอักษร',
    confirmPassword: 'ยืนยันรหัสผ่านใหม่',
    confirmPasswordGeneral: 'ยืนยันรหัสผ่าน',
    yourName: 'ชื่อของคุณ',
    messageDetails: 'รายละเอียดข้อความของคุณ...',
    contributionTopic: 'เช่น: เรื่องการแต่งงานของท่านนบี',
    contributionTopicArabic: 'عنوان بالعربية',
    contributionDetails: 'ระบุข้อกล่าวหาหรือคำถามที่ต้องการตอบ',
    contributionShortAnswer: 'สรุปคำตอบสั้นๆ ประมาณ 2-3 ประโยค',
    contributionDetailedAnswer: 'อธิบายอย่างละเอียดพร้อมหลักฐาน (รองรับ Markdown)',
    contributionSources: 'ระบุแหล่งอ้างอิง แต่ละแหล่งขึ้นบรรทัดใหม่ เช่น: صحيح البخاري، كتاب...',
    contributionTags: 'คั่นด้วยเครื่องหมายจุลภาค เช่น: ท่านนบี, การแต่งงาน, หะดีษ',
    shortAnswerSummary: 'สรุปคำตอบสั้นๆ ประมาณ 2-3 ประโยค',
    detailedAnswerMarkdown: 'อธิบายอย่างละเอียดพร้อมหลักฐาน (รองรับ Markdown)',
    sourcesReference: 'ระบุแหล่งอ้างอิง แต่ละแหล่งขึ้นบรรทัดใหม่\nเช่น: صحيح البขاري، كتاب...',
    tagsCommaSeparated: 'คั่นด้วยเครื่องหมายจุลภาค เช่น: ท่านนบี, การแต่งงาน, หะดีษ',
    topicsSearch: 'ค้นหาคำตอบ...',
  },
  labels: {
    verified: 'ได้รับการยืนยัน',
    verifiedCheck: 'ตรวจสอบแล้ว',
    logout: 'ออกจากระบบ',
    profile: 'โปรไฟล์ของฉัน',
    admin: 'จัดการระบบ',
    contribute: 'เพิ่มคำตอบ',
    login: 'เข้าสู่ระบบ',
    register: 'สมัครสมาชิก',
    adminDashboardTitle: 'คลังคำตอบชุบฮาต - ตอบข้อกล่าวหาอิสลาม',
    loading: 'กำลังโหลด...',
    checkingPermission: 'กำลังตรวจสอบสิทธิ์...',
    saving: 'กำลังบันทึก...',
    saveSuccess: 'บันทึกข้อมูลสำเร็จ',
    changePassword: 'เปลี่ยนรหัสผ่าน',
    history: 'สมาชิกตั้งแต่',
    myProfile: 'โปรไฟล์ของฉัน',
    adminPanel: 'จัดการระบบ',
    addAnswer: 'เพิ่มคำตอบ',
    viewProfile: 'ดูโปรไฟล์',
    copyright: 'สงวนลิขสิทธิ์',
    home: 'หน้าแรก',
    categories: 'หมวดหมู่',
    answersCount: 'คำตอบ',
    categoryNotFound: 'ไม่พบหมวดหมู่',
    categoryNotFoundDesc: 'หมวดหมู่ที่คุณกำลังหาอาจถูกลบหรือไม่มีในระบบ',
    allTopics: 'คำตอบทั้งหมด',
    allTopicsDesc: 'รวบรวมคำตอบสำหรับข้อกล่าวหาและข้อสงสัยเกี่ยวกับอิสลาม พร้อมหลักฐานจากอัลกุรอาน หะดีษ และนักวิชาการ',
    foundResults: 'พบ',
    resultsCountSuffix: 'คำตอบ',
    noAnswersFoundStatus: 'ไม่พบคำตอบ',
    noAnswersFiltered: 'ลองเปลี่ยนคำค้นหาหรือตัวกรองเพื่อดูผลลัพธ์เพิ่มเติม',
    noAnswersInSystem: 'ยังไม่มีคำตอบในระบบ',
    contactUs: 'ติดต่อเรา',
    principles: {
      evidence: { title: 'หลักฐานเป็นฐาน', desc: 'ทุกคำตอบอ้างอิงจากอัลกุรอาน หะดีษ และความเห็นนักวิชาการ' },
      accuracy: { title: 'ความถูกต้อง', desc: 'ตรวจสอบความถูกต้องของหลักฐานก่อนนำเสนอ' },
      academic: { title: 'วิชาการ', desc: 'นำเสนอด้วยหลักวิชาการและเหตุผลที่ชัดเจน' },
      accessible: { title: 'เข้าถึงง่าย', desc: 'อธิบายเนื้อหายากให้เข้าใจง่ายสำหรับทุกคน' },
    },
    aboutQuote: {
      arabic: 'وَقُلْ جَاءَ الْحَقُّ وَزَهَقَ الْبَاطิลُ ۚ إِنَّ الْبَاطِلَ كَانَ زَهُوقًا',
      thai: '"และจงกล่าวเถิดว่า ความจริงได้มาแล้ว และความเท็จได้มลายไป แท้จริงความเท็จนั้นเป็นสิ่งที่ต้องมลายไป"',
      source: '- ซูเราะฮ์อัลอิสรออ์ 17:81',
    },
    scholarVerificationNote: 'ทุกคำตอบจะผ่านการตรวจสอบจากนักวิชาการก่อนเผยแพร่',
    basicMethodology: 'หลักการพื้นฐาน',
    workProcess: 'ขั้นตอนการทำงาน',
    evidenceTypes: 'ประเภทหลักฐานที่ใช้',
    methodologyCTA: 'มีคำถามเกี่ยวกับหลักการของเรา?',
    searchTitle: 'ค้นหาคำตอบ',
    searchDesc: 'พิมพ์คำค้นหาเพื่อค้นหาคำตอบที่คุณต้องการ',
    popularSearches: 'คำค้นหายอดนิยม',
    foundResultsPrefix: 'พบ',
    foundResultsSuffix: 'ผลลัพธ์ สำหรับ',
    orBrowseCategories: 'หรือเลือกตามหมวดหมู่',
    noResultsFound: 'ไม่พบผลลัพธ์',
    noResultsMatching: 'ไม่พบคำตอบที่ตรงกับ',
    checkSpelling: 'ลองใช้คำอื่นหรือตรวจสอบการสะกดคำ',
    viewAllAnswers: 'ดูคำตอบทั้งหมด',
    chooseCategory: 'เลือกหมวดหมู่',
    contributeTitle: 'เพิ่มคำตอบใหม่',
    contributeDesc: 'สร้างเนื้อหาสำหรับ Haqq Vault',
    tabNew: 'สร้างใหม่',
    tabDrafts: 'แบบร่าง',
    tabPublished: 'เผยแพร่แล้ว',
    checkingAuth: 'กำลังตรวจสอบสิทธิ์...',
    contributeSuccess: 'บันทึกสำเร็จ!',
    contributeSuccessDesc: 'คำตอบของคุณถูกบันทึกเรียบร้อยแล้ว',
    labelTitleThai: 'หัวข้อ (ภาษาไทย) *',
    labelTitleArabic: 'หัวข้อ (ภาษาอาหรับ)',
    labelClaim: 'ข้อกล่าวหา / คำถาม *',
    labelCategory: 'หมวดหมู่ *',
    labelSeverity: 'ระดับความสำคัญ',
    labelShortAnswer: 'คำตอบสั้น *',
    labelDetailedAnswer: 'คำตอบเชิงลึก *',
    markdownSupport: 'รองรับ Markdown สำหรับการจัดรูปแบบ',
    labelSources: 'แหล่งอ้างอิง',
    labelTags: 'แท็ก',
    publish: 'เผยแพร่',
    saveAsDraft: 'บันทึกเป็นแบบร่าง',
    noDrafts: 'ยังไม่มีแบบร่าง',
    noPublished: 'ยังไม่มีคำตอบที่เผยแพร่',
    myProfileTitle: 'โปรไฟล์ของฉัน',
    myProfileDesc: 'จัดการข้อมูลส่วนตัวของคุณ',
    personalInfo: 'ข้อมูลส่วนตัว',
    displayName: 'ชื่อแสดง',
    aboutMe: 'เกี่ยวกับตัวคุณ',
    memberSince: 'สมาชิกตั้งแต่',
    edit: 'แก้ไข',
    save: 'บันทึก',
    cancel: 'ยกเลิก',
    security: 'ความปลอดภัย',
    password: 'รหัสผ่าน',
    changePasswordDesc: 'เปลี่ยนรหัสผ่านของคุณ',
    emailVerification: 'ยืนยันอีเมล',
    verifiedStatus: 'ยืนยันแล้ว',
    unverifiedStatus: 'ยังไม่ได้ยืนยัน',
    sendVerificationLink: 'ส่งลิงก์ยืนยัน',
    topicNotFound: 'ไม่พบคำตอบ',
    backToHome: 'กลับสู่หน้าหลัก',
    backToCategories: 'กลับไปดูหมวดหมู่ทั้งหมด',
    errorOccurred: 'เกิดข้อผิดพลาด',
    deleteLabel: 'ลบ',
    pleaseWait: 'กรุณารอสักครู่',
    lastUpdated: 'อัปเดตล่าสุด',
    contactTitle: 'ติดต่อเรา',
    contactDesc: 'มีคำถาม ข้อเสนอแนะ หรือต้องการส่งคำถามใหม่? ติดต่อเราได้ที่นี่',
    submitSuccess: 'ส่งข้อความสำเร็จ!',
    submitSuccessDesc: 'ขอบคุณที่ติดต่อเรา เราจะตอบกลับโดยเร็วที่สุด',
    sendAgain: 'ส่งข้อความอีกครั้ง',
    sendMessageTitle: 'ส่งข้อความถึงเรา',
    labelName: 'ชื่อ *',
    labelEmail: 'อีเมล *',
    labelSubject: 'หัวข้อ *',
    labelMessage: 'ข้อความ *',
    chooseSubject: 'เลือกหัวข้อ',
    subjectQuestion: 'ส่งคำถามใหม่',
    subjectCorrection: 'แจ้งข้อผิดพลาด',
    subjectSuggestion: 'ข้อเสนอแนะ',
    subjectCollaboration: 'ร่วมมือกับเรา',
    subjectOther: 'อื่นๆ',
    sending: 'กำลังส่ง...',
    sendMessage: 'ส่งข้อความ',
    contactChannels: 'ช่องทางติดต่อ',
    sendNewQuestion: 'ส่งคำถามใหม่',
    sendNewQuestionDesc: 'หากคุณมีคำถามหรือพบข้อกล่าวหาที่ยังไม่มีคำตอบ สามารถส่งให้เราพิจารณาได้',
    instructionClearQuestion: 'ระบุคำถามหรือข้อกล่าวหาให้ชัดเจน',
    instructionAttachSource: 'แนบแหล่งที่มา (ถ้ามี)',
    instructionResponse: 'เราจะพิจารณาและตอบกลับ',
    contactQuote: {
      arabic: 'ادْعُ إِلَى سَبِيلِ رَبِّكَ بِالْحِكْمَةِ وَالْمَوْعِظَةِ الْحَسَنَةِ',
      thai: '"จงเชิญชวนสู่ทางของพระผู้อภิบาลของเจ้าด้วยวิทยปัญญาและการตักเตือนที่ดี"',
      source: '- ซูเราะฮ์อันนะฮ์ล 16:125',
    },
    emailLabel: 'อีเมล',
    facebookLabel: 'Facebook',
    twitterLabel: 'Twitter / X',
  },
  roles: {
    admin: 'ผู้ดูแล',
    adminFull: 'ผู้ดูแลระบบ',
    scholar: 'นักวิชาการ',
    member: 'สมาชิก',
  },
  severity: {
    basic: 'พื้นฐาน',
    intermediate: 'ปานกลาง',
    advanced: 'ขั้นสูง',
  },
  // Top-level labels for backward compatibility
  categoriesTitle: 'หมวดหมู่คำตอบ',
  categoriesDescription: 'เลือกหมวดหมู่ที่สนใจเพื่อค้นหาคำตอบที่เหมาะกับคุณ',
  addingContinuous: 'เรากำลังเพิ่มเติมคำตอบอย่างต่อเนื่อง',
  viewAll: 'ดูทั้งหมด',
  backToAllCategories: 'กลับไปดูหมวดหมู่ทั้งหมด',
  noTopicsInCategory: 'ยังไม่มีคำตอบในหมวดหมู่นี้',
  noAnswersFound: 'ไม่พบคำตอบ',
  clearFilters: 'ล้างตัวกรอง',
  allLevels: 'ทุกระดับ',
  allCategories: 'ทุกหมวดหมู่',
  sortByNewest: 'ใหม่ล่าสุด',
  sortByPopularSymbol: 'ยอดนิยม',
  aboutTitle: 'เกี่ยวกับ Haqq Vault',
  aboutArabic: 'حق والต์',
  aboutSlogan: 'คลังคำตอบชุบฮาต',
  ourMission: 'พันธกิจของเรา',
  ourPrinciples: 'หลักการของเรา',
  ourSources: 'แหล่งอ้างอิงของเรา',
  readyToExplore: 'พร้อมที่จะค้นหาความจริงแล้วหรือยัง?',
  scholarsTitle: 'คณะนักวิชาการ',
  scholarsDescription: 'ผู้เชี่ยวชาญที่ร่วมตรวจสอบและให้ข้อมูลเพื่อความถูกต้องของเนื้อหา',
  methodologyTitle: 'กระบวนการทำงาน',
  methodologyDescription: 'มาตรฐานที่เราใช้ในการคัดเลือก ตรวจสอบ และสรุปคำตอบ',
  researchProcess: 'กระบวนการวิจัย',
  verificationProcess: 'กระบวนการตรวจสอบ',
  publicationProcess: 'กระบวนการเผยแพร่',
  popularTitle: 'คำตอบยอดนิยม',
  popularDescription: 'คำตอบที่ได้รับความสนใจและมีผู้เข้าชมมากที่สุด',
  viewsCount: 'เข้าชม',
  loginTitle: 'เข้าสู่ระบบ',
  loginArabic: 'تسجيل الدخول',
  loginSubtitle: 'ยินดีต้อนรับสู่ Haqq Vault',
  dontHaveAccount: 'ยังไม่มีบัญชี?',
  forgotPasswordLabel: 'ลืมรหัสผ่าน?',
  verifyEmailTitle: 'ยืนยันอีเมล',
  verifyEmailArabic: 'تحقق من البريد الإلكتروني',
  verifyEmailSubtitle: 'กรุณาตรวจสอบอีเมลของคุณเพื่อยืนยันบัญชี',
  forgotPasswordTitle: 'ลืมรหัสผ่าน',
  forgotPasswordArabic: 'نسيت كلمة المرور',
  forgotPasswordSubtitle: 'เราจะส่งลิงก์สำหรับตั้งรหัสผ่านใหม่ไปให้คุณ',
  termsTitle: 'เงื่อนไขการใช้งาน',
  privacyTitle: 'นโยบายความเป็นส่วนตัว',
  lastUpdated: 'อัปเดตล่าสุด',
  welcomeBack: 'ยินดีต้อนรับกลับ',
  loginToContinue: 'เข้าสู่ระบบเพื่อดำเนินการต่อ',
  rememberMe: 'จดจำฉัน',
  loginLoading: 'กำลังเข้าสู่ระบบ...',
  orWith: 'หรือ',
  continueWithGoogle: 'ดำเนินการต่อด้วย Google',
  registerNow: 'สมัครสมาชิก',
  quickLogin: 'เข้าสู่ระบบด่วน',
  clickToAutoLogin: '(คลิกเพื่อ Auto Login)',
  checkYourEmail: 'ตรวจสอบอีเมลของคุณ',
  resetLinkSent: 'เราจะส่งลิงก์สำหรับรีเซ็ตรหัสผ่านให้คุณ',
  resendLink: 'ส่งใหม่อีกครั้ง',
  backToLogin: 'กลับไปเข้าสู่ระบบ',
  sending: 'กำลังส่ง...',
  sendResetLink: 'ส่งลิงก์รีเซ็ตรหัสผ่าน',
  verifyEmailSuccess: 'ยืนยันอีเมลสำเร็จ!',
  verifyEmailError: 'ยืนยันอีเมลไม่สำเร็จ',
  pleaseWait: 'กรุณารอสักครู่',
  verifyingEmail: 'กำลังยืนยันอีเมล...',
  requestNewLink: 'ขอลิงก์ใหม่',
} as const;
